apiVersion: v1
kind: ReplicationController # 资源对象的类型，这里是副本控制器
metadata:
  name: mysql               
spec:                     # spec 说明书。ReplicationController相关属性定义。
  replicas: 1             # POD 期望的副本数
  selector:               # 标签选择器。
    app: mysql            # 副本拥有的标签。
  template:               # 定义  POD 实例的模板。
    metadata:
      labels:
        app: mysql        # 指定 pod 的标签，要与 selector 中的相同。
    spec:
      containers:         # 定义容器。
        - name: mysql
          image: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSOWED
            value: "123456"
# create command: kubectl create -f mysql-rc.yaml
