apiVersion: v1
kind: Service       # 类型为服务
metadata:
  name: myweb       # service 全局名称
spec:
  type: NodePort    # NodePort方式的外网访问模式
  ports:
    - port: 8080    # service 的虚拟端口。
      nodePort: 30001  # 外部访问的端口
  selector:         # 指定 service 的 POD 的对应的标签。
    app: myweb